//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechZoneAdminWinFormsTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechZoneAdminWinFormsTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string ConfirmPasswordHint {
            get {
                return ResourceManager.GetString("ConfirmPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        internal static string DefaultErrorMessage {
            get {
                return ResourceManager.GetString("DefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An information message..
        /// </summary>
        internal static string DefaultInfoMessage {
            get {
                return ResourceManager.GetString("DefaultInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultProfileImage {
            get {
                object obj = ResourceManager.GetObject("DefaultProfileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Profile.
        /// </summary>
        internal static string DefaultProfileText {
            get {
                return ResourceManager.GetString("DefaultProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields..
        /// </summary>
        internal static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg;*.png.
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding product: {0}.
        /// </summary>
        internal static string LoggingProductRepository_Add_Adding_product___0_ {
            get {
                return ResourceManager.GetString("LoggingProductRepository_Add_Adding_product___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting product ID: {0}.
        /// </summary>
        internal static string LoggingProductRepository_Delete_Deleting_product_ID___0_ {
            get {
                return ResourceManager.GetString("LoggingProductRepository_Delete_Deleting_product_ID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering products: Name={0}, Price={1}, Stock={2}, Category={3}, Specs={4}.
        /// </summary>
        internal static string LoggingProductRepository_Filter_Filtering_products___Name__0__Price__1__Stock__2__Category__3__Specs__4_ {
            get {
                return ResourceManager.GetString("LoggingProductRepository_Filter_Filtering_products___Name__0__Price__1__Stock__2_" +
                        "_Category__3__Specs__4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all products....
        /// </summary>
        internal static string LoggingProductRepository_GetAll_Getting_all_products___ {
            get {
                return ResourceManager.GetString("LoggingProductRepository_GetAll_Getting_all_products___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting product by ID: {0}.
        /// </summary>
        internal static string LoggingProductRepository_GetById_Getting_product_by_ID___0_ {
            get {
                return ResourceManager.GetString("LoggingProductRepository_GetById_Getting_product_by_ID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating product ID: {0}.
        /// </summary>
        internal static string LoggingProductRepository_Update_Updating_product_ID___0_ {
            get {
                return ResourceManager.GetString("LoggingProductRepository_Update_Updating_product_ID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful!.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        internal static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string MenuProducts {
            get {
                return ResourceManager.GetString("MenuProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string MessageBoxInfoTitle {
            get {
                return ResourceManager.GetString("MessageBoxInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPasswordHint {
            get {
                return ResourceManager.GetString("NewPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed: {0}.
        /// </summary>
        internal static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful..
        /// </summary>
        internal static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        internal static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        internal static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0}!.
        /// </summary>
        internal static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
    }
}
